name: studenthive
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.10
  go_router: ^12.1.3
  image_picker: ^1.0.7
  lottie: ^2.7.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/icons/icon.png 
  color: "FFFFFF" 

flutter:
  uses-material-design: true
  assets:
    - assets/animations/animartion_prueba.json
    - assets/animations/loading.json
    - assets/animations/aprober.json
    - assets/animations/location.json
    - assets/animations/casa-prueba.json
    - assets/animations/casa.json
